version: '3.5'
services:
  gatewayservice:
    image: jugadorgraphy/gateway
    ports:
      - "5000:80"
    depends_on:
      - consul
  emailservice:
    image: jugadorgraphy/emailapi
    ports:
      - "5001:80"
    environment:
      consulserver: "http://consul:8500"
    depends_on:
      - consul
  # name of service
  userservice:
    image: jugadorgraphy/userapi
    ports:
      # mapping of port
      - "5002:80"
    environment:
      # specify connection string of sql server to match the name of the sql container
      BusyBeesUserDB: "Server=sqldb; Initial Catalog=BZBUserDB; User Id=sa; password=pass@123"
      consulserver: "http://consul:8500"
    depends_on:
      - consul
  favservice:
    image: jugadorgraphy/favapi
    ports:
      - "5003:80"
    environment:
      BusyBeesFavDB: "mongodb://mongodb:27017"
      consulserver: "http://consul:8500"
    depends_on:
      - consul
  frontendservice:
    image: jugadorgraphy/busybees-transportapp
    ports:
      - "9000:80"
  # name of container for databases
  sqldb:
    # name of image for sql server
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      # map the port number to match the one on the local system
      - "1433:1433"
    environment:
      - SA_PASSWORD=pass@123
      # to accept EULA
      - ACCEPT_EULA=Y
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  consul:
    image: consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_BIND_INTERFACE: eth0
